version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: aave_v4_liquidation_bot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder
      POSTGRES_DB: ponder
    ports:
      - "5432:5432"
    volumes:
      - aave_v4_liquidation_bot_postgres:/var/lib/postgresql/data

volumes:
  aave_v4_liquidation_bot_postgres:

